extends Node2D

# warning-ignore:unused_signal
#signal stone_hit
# warning-ignore:unused_signal
signal coin_picked
# warning-ignore:unused_signal
signal update_money
#signal update_score
# warning-ignore:unused_signal
signal game_over
# warning-ignore:unused_signal
signal world_stopped
# warning-ignore:unused_signal
signal attack_damage
# warning-ignore:unused_signal
signal attack_finished
# warning-ignore:unused_signal
signal killed
# warning-ignore:unused_signal
signal being_attacked
# warning-ignore:unused_signal
signal health_changed
# warning-ignore:unused_signal
signal one_hit_killed
# warning-ignore:unused_signal
signal object_created
# warning-ignore:unused_signal
signal ready_to_start
